apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-pv
spec:
  capacity:
    storage: 10Gi  # Size of the EBS volume
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual-ebs  # Custom storage class
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-0921fbe4d6878be29  # The ID of the pre-existing EBS volume
    fsType: ext4
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: topology.ebs.csi.aws.com/zone
              operator: In
              values:
                - us-east-1a  # The Availability Zone where the EBS volume is located
