apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual-ebs  # It should match the storage class name from the PV
  resources:
    requests:
      storage: 10Gi  # It should match the size of the PV
